version: '3.8'

x-environment-defaults: &environment-defaults
  DEBUG: "False"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"


services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - .env:/tld/.env.docker
      - static_volume:/app/static/
    networks:
      - prediction-network
    expose:
      - 8000
    environment:
      <<: *environment-defaults


    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application




  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      networks:
        - prediction-network




  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info
    networks:
      - prediction-network
    volumes:
      - ./:/tld
    depends_on:
      - redis


  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - static_volume:/static
      ports:
        - "80:80"
      networks:
        - prediction-network
      depends_on:
        - web


volumes:
  pg_data:
  static_volume:

networks:
  prediction-network:
    driver: bridge