# Generated by Django 5.1.1 on 2024-10-18 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companyuser_is_driver'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company'),
        ),
    ]
