# Generated by Django 5.1.2 on 2024-10-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id chat')),
                ('companion_id', models.IntegerField(verbose_name='id driver')),
                ('my_id', models.IntegerField(verbose_name='operator id')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('user_id', models.IntegerField(verbose_name='id user chat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagesandchat.chat')),
            ],
        ),
    ]
