# Generated by Django 5.1.2 on 2024-10-16 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesandchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='my_id',
            field=models.IntegerField(blank=True, verbose_name='operator id'),
        ),
    ]
