# Generated by Django 5.1.1 on 2024-10-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesandchat', '0002_alter_chat_chat_id_alter_chat_my_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='companion_id',
            field=models.IntegerField(verbose_name='companion id'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='my_id',
            field=models.IntegerField(blank=True, verbose_name='my id'),
        ),
    ]
