# Generated by Django 5.1 on 2024-08-22 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Company Name')),
                ('phone', models.CharField(max_length=18, verbose_name='phone')),
                ('usdot', models.CharField(max_length=100, verbose_name='usdot')),
                ('home_terminal_address', models.CharField(max_length=50, verbose_name='home_terminal_address')),
                ('home_terminal_timezone', models.CharField(choices=[('Alaska Daylight Time', 'Alaska Daylight Time'), ('Central Daylight Time', 'Central Daylight Time'), ('Eastern Daylight Time', 'Eastern Daylight Time'), ('Hawaii Standard Time', 'Hawaii Standard Time'), ('Mountain Daylight Time', 'Mountain Daylight Time'), ('Pheonix Standart Time', 'Pheonix Standart Time'), ('Pacific Daylight Time', 'Pacific Daylight Time')], max_length=50, verbose_name='home_terminal_timezone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('company_address', models.CharField(max_length=60, verbose_name='company_address')),
                ('owner', models.BooleanField(default=False, verbose_name='owner')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('activation_code', models.CharField(blank=True, max_length=60, null=True, verbose_name='activation_code')),
                ('delete_code', models.CharField(blank=True, max_length=60, null=True, verbose_name='delete_code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Loads viewer (read only)', 'Loads viewer (read only)'), ('Loads only', 'Loads only'), ('Logbook and Loads ', 'Logbook and Loads'), ('Logbook only', 'Logbook only'), ('Accounting', 'Accounting'), ('Super Dispatcher', 'Super Dispatcher'), ('Service Account', 'Service Account')], max_length=200, verbose_name='role')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
