# Generated by Django 5.1 on 2024-08-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companyuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Loads viewer (read only)', 'Loads viewer (read only)'), ('Loads only', 'Loads only'), ('Logbook and Loads ', 'Logbook and Loads'), ('Logbook only', 'Logbook only'), ('Accounting', 'Accounting'), ('Super Dispatcher', 'Super Dispatcher'), ('Service Account', 'Service Account')], max_length=200, verbose_name='role'),
        ),
    ]
