# Generated by Django 5.1 on 2024-08-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companyuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='role',
        ),
    ]
