# Generated by Django 5.1.1 on 2024-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_companyuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='user is driver ?'),
        ),
    ]
