# Generated by Django 5.1 on 2024-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usdot',
            field=models.IntegerField(max_length=100),
        ),
    ]
