# Generated by Django 5.1 on 2024-08-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_co_driver_customuser_drivers_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address1',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='address1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address2',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='address2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='colors',
            field=models.CharField(blank=True, choices=[('Yellow', 'Yellow'), ('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red'), ('Blue', 'Blue'), ('Cyan-Blue', 'Cyan-Blue'), ('Tealish Green', 'Tealish Green'), ('Magenta', 'Magenta'), ('Purple', 'Purple'), ('Red-Orange', 'Red-Orange'), ('Grey', 'Grey'), ('Bluewood', 'Bluewood'), ('Default color', 'Default color')], max_length=50, null=True, verbose_name='Colors'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='co_driver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='co_driver'),
        ),
    ]
