# Generated by Django 5.1.1 on 2024-09-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_personal_conveyance',
            field=models.BooleanField(default=False, verbose_name='Allow Personal Conveyance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='allow_yard_move',
            field=models.BooleanField(default=False, verbose_name='Allow Yard Move'),
        ),
    ]
