# Generated by Django 5.1.1 on 2024-10-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_drivers_license_issuing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_terminal_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Home Terminal Address'),
        ),
    ]
