# Generated by Django 5.1.1 on 2024-10-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customuser_home_terminal_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
    ]
