# Generated by Django 5.1.1 on 2024-10-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
